### PR TITLE
Added zone info + zone update calls

### PR DESCRIPTION
**Pull request by websmurf**
Added support for [zoneinfo](https://dm.realtimeregister.com/docs/api/domains/zoneinfo) and [update](https://dm.realtimeregister.com/docs/api/domains/zoneupdate)

~~There is a bit of clutter in this pull request, since it also includes the changes in #64 (I forked it from that one)~~

### CODE REVIEW

**Comment by websmurf** [comment]
Rebased and fixed the php 7.4 error

**Review by arnowest — CHANGES_REQUESTED** [review]
According to the RTR documentation the records set in a zone update is optional. Can you make the `$records` parameters of the `zoneUpdate` nullable?

**Comment by websmurf** [comment]
@arnowest yes, done!

**Comment by arnowest** [comment]
> @arnowest yes, done!

Great! Thanks for these calls!

**Review by arnowest — APPROVED** [review]

**Pull request merged**
